version: '3.8'

services:

 app:
   build: .
   container_name: node_app
   ports:
     - "3000:3000"
   depends_on:
     - mongo
   networks:
     - mynetwork

 mongo:
   image: mongo:latest
   container_name: mongo_db
   ports:
     - "27017:27017"
   networks:
     - mynetwork

networks:
 mynetwork:
